version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root-secret
      MYSQL_DATABASE: BookYourSlot
      MYSQL_USER: CodeWithSrb
      MYSQL_PASSWORD: srb-secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bookyourslot-network
  app:
    build: .
    container_name: bookyourslot-app
    ports:
      - "9080:8080"
    environment:
      MYSQL_HOST: mysql_db
      MYSQL_USER: CodeWithSrb
      MYSQL_PASSWORD: srb-secret
      MYSQL_PORT: 3306
    depends_on:
      - mysql
    networks:
      - bookyourslot-network

volumes:
  mysql_data:

networks:
  bookyourslot-network:
    driver: bridge
