spring:
  datasource:
    url: jdbc:mysql://produrl:3307/BookYourSlot
    username: root
    password: srb-secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  sql:
    init:
      mode: never
      continue-on-error: false