jwt:
  secret:

logging:
  level:
    org.springframework.security: TRACE

server:
  error:
    path: /api/v1/booking/error
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BookYourSlot
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  sql:
    init:
      mode: never
      continue-on-error: false